image: java:8-jdk

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - analyze
  - publish

cache:
  group: swagger_confluence
  key: "$CI_BUILD_REF_NAME"
  paths:
     - .gradle/wrapper
     - .gradle/caches

job_build_develop:
  stage: build
  script:
    - ./gradlew clean build
  only:
    - develop
  tags:
    - docker

job_build_master:
  stage: build
  script:
    - ./gradlew clean build -Prelease=true
  only:
    - master
  tags:
    - docker

job_analyze_develop:
  stage: analyze
  script:
    - ./gradlew jacocoTestReport sonarqube
  only:
    - develop
  tags:
    - docker

job_publish:
  stage: publish
  only:
    - develop
    - master
  script:
    - ./gradlew publish
  artifacts:
    paths:
    - swagger-confluence-core/build/libs/*.jar
    - swagger-confluence-gradle-plugin/build/libs/*.jar
  tags:
    - docker

